BlizzTrack/Pages/Admin/Index.cshtml.cs
using BlizzTrack.Helpers;
using Core.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.FeatureManagement.Mvc;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace BlizzTrack.Pages.Admin
{
    [FeatureGate(nameof(FeatureFlags.AdminPanel))]
    [Authorize(Roles = "Admin")]
    public class IndexModel : PageModel
    {
        private readonly IGameConfig _gameConfig;

        [BindProperty(SupportsGet = true, Name = "search")]
        public string Search { get; set; }

        public IndexModel(IGameConfig gameConfig)
        {
            _gameConfig = gameConfig;
        }

        public List<Core.Models.GameConfig> Configs;

        public async Task OnGetAsync()
        {
            Configs = await _gameConfig.All();
        }
    }
}

BlizzTrack/Pages/Admin/ModifyGame.cshtml.cs
using BlizzTrack.Helpers;
using Core.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Configuration;
using Microsoft.FeatureManagement.Mvc;
using Minio;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace BlizzTrack.Pages.Admin
{
    public class GameInfoModel
    {
        [Required]
        [Display(Name = "Game Name")]
        public string GameName { get; set; }

        [Display(Name = "Game Website")]
        [Url]
        public string GameWebsite { get; set; }

        [Display(Name = "Service Alert Icon Path")]
        public string ServiceAlertPath { get; set; }
    }

    [FeatureGate(nameof(FeatureFlags.AdminPanel))]
    [Authorize(Roles = "Admin")]
    public class ModifyGameModel : PageModel
    {
        private readonly IGameConfig _gameConfig;
        private readonly MinioClient _minioClient;
        private readonly string _bucket;
        private readonly Core.Models.DBContext _dbContext;

        public ModifyGameModel(IGameConfig gameConfig, MinioClient minioClient, IConfiguration config, Core.Models.DBContext dbContext)
        {
            _gameConfig = gameConfig;
            _minioClient = minioClient;
            _bucket = config.GetValue("AWS:BucketName", "");
            _dbContext = dbContext;
        }

        [BindProperty(SupportsGet = true, Name = "game")]
        public string GameCode { get; set; }

        [BindProperty]
        public GameInfoModel GameInfoModel { get; set; }

        public Core.Models.GameConfig GameInfo;

        public async Task OnGetAsync()
        {
            GameInfo = await _gameConfig.Get(GameCode);
            if (GameInfo == null)
            {
                NotFound();
                return;
            }

            GameInfoModel ??= new GameInfoModel
            {
                GameName = GameInfo.GetName(),
                GameWebsite = GameInfo.Website,
                ServiceAlertPath = GameInfo.ServiceURL
            };
        }

        public async Task<IActionResult> OnPostUpdateGameAsync()
        {
            GameInfo = await _gameConfig.Get(GameCode);

            if (!ModelState.IsValid)
                return Page();

            GameInfo.Name = GameInfoModel.GameName;
            GameInfo.Website = GameInfoModel.GameWebsite;
            GameInfo.ServiceURL = GameInfoModel.ServiceAlertPath;

            _dbContext.GameConfigs.Update(GameInfo);
            await _dbContext.SaveChangesAsync();

            return Redirect(HttpContext.Request.Path);
        }
    }
}

BlizzTrack/Pages/Admin/Index.cshtml
@page
@model BlizzTrack.Pages.Admin.IndexModel
@{
    ViewData["Title"] = "Dashboard";
}

<div class="row">
    <div class="col-12" aria-label="breadcrumb col-12" role="navigation">
        <ol class="breadcrumb">
            <li class="breadcrumb-item active">All Games</li>
        </ol>
    </div>
    
    <div class="col-12">
        <div class="card ">
            <div class="card-header">
                <div class="col-sm-12 text-left">
                    <h2 class="card-title">All games indexed games</h2>
                    <h5 class="card-category">This is the games from the current manifest</h5>
                </div>
            </div>
            <div class="card-body">
                <div class="table-responsive ps">
                    <table class="table tablesorter table-hover" id="">
                        <thead class=" text-primary">
                            <tr>
                                <th style="width: 25px;" data-toggle="tooltip" data-placement="right" title="Is game encrypted">
                                    <i class="fa fa-lock"></i>
                                </th>
                                <th>
                                    Name
                                </th>
                                <th>
                                    Code
                                </th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var game in Model.Configs)
                            {
                                <tr>
                                    <td>
                                        <i class="fa fa-@(game.Config.Encrypted ? "lock" : "lock-open")"></i>
                                    </td>
                                    <td>
                                        @(string.IsNullOrEmpty(game.Name) ? BNetLib.Helpers.GameName.Get(game.Code) : game.Name)
                                    </td>
                                    <td>
                                        @(game.Code)
                                    </td>
                                    <td class="text-right">
                                        <a asp-page="/Admin/ModifyGame" asp-route-game="@game.Code">Modify Game Config</a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

BlizzTrack/Pages/Admin/ModifyGame.cshtml
@page "/admin/modify-game/{game}"
@model BlizzTrack.Pages.Admin.ModifyGameModel
@{
    ViewData["Title"] = $"Modifying {Model.GameInfo.GetName()}";
}

<div class="row">
    <div class="col-12" aria-label="breadcrumb col-12" role="navigation">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a asp-page="/Admin/Index">All Games</a>
            </li>
            <li class="breadcrumb-item active">@ViewData["Title"]</li>
        </ol>
    </div>
    
    <div class="col-sm-12 col-md-12">
        <div class="card">
            <div class="card-header">
                <h5 class="title">Edit Game Info</h5>
            </div>
            <form method="post" asp-page-handler="UpdateGame" enctype="multipart/form-data">
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                @Html.LabelFor(x => x.GameInfoModel.GameName)
                                @Html.TextBoxFor(x => x.GameInfoModel.GameName, new { placeholder = "Game Name", @class = "form-control mb-1" })
                                @Html.ValidationMessageFor(x => x.GameInfoModel.GameName, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                @Html.LabelFor(x => x.GameInfoModel.GameWebsite)
                                @Html.TextBoxFor(x => x.GameInfoModel.GameWebsite, new { placeholder = "Game Website", @class = "form-control mb-1" })
                                @Html.ValidationMessageFor(x => x.GameInfoModel.GameWebsite, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                @Html.LabelFor(x => x.GameInfoModel.ServiceAlertPath)
                                @Html.TextBoxFor(x => x.GameInfoModel.ServiceAlertPath, new { placeholder = "Game Service Alert Path (not full URL)", @class = "form-control mb-1" })
                                @Html.ValidationMessageFor(x => x.GameInfoModel.ServiceAlertPath, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-fill btn-primary">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>